export const ADD_TODO = 'EDIT_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const TOGGLE_COMPLETE_TODO = 'TOGGLE_COMPLETE_TODO';
export const TOGGLE_BOOKMARK_TODO = 'TOGGLE_BOOKMARK_TODO';
export const TOGGLE_DELETE_TODO = 'TOGGLE_DELETE_TODO';
export const EMPTY_TODOS = 'EMPTY_TODOS';
